'use strict';
const staff=document.body.dataset.staff==='true',prefix=staff?'/api/admin/workspace/':'/api/client/';
const $=id=>document.getElementById(id);let csrf='',role='',current=null;
let invite=staff?null:new URLSearchParams(location.hash.slice(1)).get('invite');
if(invite){history.replaceState(null,'',location.pathname);$('login').hidden=true;$('activate').hidden=false;}
function el(tag,content,cls){const node=document.createElement(tag);if(content!==undefined)node.textContent=content;if(cls)node.className=cls;return node;}
function stamp(n){return n?new Date(n*1000).toLocaleString(): '—';}
function money(p){return new Intl.NumberFormat(undefined,{style:'currency',currency:p.currency}).format(p.minor_units/100);}
async function api(path,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:controller.signal,...(data!==undefined?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok){if(response.status===401&&csrf)clear();throw Error(result.error||'Unable to complete the request.');}return result;}finally{clearTimeout(timer);}}
function clear(){csrf='';current=null;$('project').replaceChildren();$('project-list').replaceChildren();$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;if(staff){$('report').replaceChildren();$('loss-report').replaceChildren();}}
async function act(fn,success='Saved.'){try{await fn();$('message').textContent=success;}catch(e){$('message').textContent=e.name==='AbortError'?'The request timed out. Refresh to check whether it was saved before retrying.':e.message;}}
function button(label,fn){const b=el('button',label);b.type='button';b.addEventListener('click',()=>{b.disabled=true;act(fn).finally(()=>b.disabled=false);});return b;}
function field(form,label,key,type='text',choices=null){const id='f-'+Math.random().toString(36).slice(2);const l=el('label',label);l.htmlFor=id;const input=el(choices?'select':type==='textarea'?'textarea':'input');input.id=id;input.name=key;if(!choices&&type!=='textarea')input.type=type;if(choices)for(const v of choices){const o=el('option',v);o.value=v;input.append(o);}form.append(l,input);return input;}
function formBox(parent,title,submit){const box=el('details'),summary=el('summary',title),form=el('form');box.append(summary,form);parent.append(box);const save=el('button','Save');save.type='submit';form.addEventListener('submit',e=>{e.preventDefault();save.disabled=true;act(async()=>{await submit(form);await loadProject();},'Saved.').finally(()=>save.disabled=false);});queueMicrotask(()=>form.append(save));return form;}
async function change(action,data){if(!current)throw Error('Choose a project.');return api(prefix+action,{reference:current.reference,...(staff?{version:current.version}:{}),...data});}
async function load(){const result=await api(prefix+'projects'),selected=$('project-list').value;$('project-list').replaceChildren(...result.projects.map(p=>{const o=el('option',p.title+' · '+p.reference);o.value=p.reference;return o;}));if(result.projects.some(p=>p.reference===selected))$('project-list').value=selected;await loadProject();if(staff)await report();}
async function report(){const r=await api(prefix+'report?days='+$('report-days').value);const labels={enquiries:'Enquiries',demoReserved:'Reserved a demo',proposalProjects:'Published proposal',acceptedProjects:'Accepted proposal',overdueFollowups:'Overdue follow-ups',openTickets:'Active support tickets',overdueTickets:'Overdue support targets'};$('report').replaceChildren(...Object.entries(r.counts).map(([k,v])=>{const n=el('div',labels[k]||k);n.append(el('strong',String(v)));return n;}));const rate=r.counts.enquiries?(100*r.counts.demoReserved/r.counts.enquiries).toFixed(1)+'%':'—',accept=r.counts.proposalProjects?(100*r.counts.acceptedProjects/r.counts.proposalProjects).toFixed(1)+'%':'—';$('report-basis').textContent='Enquiry → demo: '+rate+'. Published proposal → acceptance: '+accept+'. '+r.basis;$('loss-report').replaceChildren(el('h3','Current lost-deal reasons'),...Object.entries(r.lostReasons).map(([k,v])=>el('p',k+': '+v)));}
async function loadProject(){const ref=$('project-list').value;if(!ref){current=null;$('project').replaceChildren(el('p','No projects are available.'));return;}current=await api(prefix+'project?reference='+encodeURIComponent(ref));render();}
function render(){const p=current,root=$('project');root.replaceChildren();const overview=el('section');overview.append(el('h2',p.title),el('p','Reference: '+p.reference+' · '+p.status),el('p','Client: '+p.email));root.append(overview);
 if(staff){if(role!=='agent'){overview.append(button('Send access / password reset invitation',async()=>{if(!confirm('Send a private password setup link to '+p.email+'?'))return;await change('invite',{});await loadProject();}),button('Disable client access',async()=>{if(!confirm('Disable this client account across all its projects and revoke its sessions?'))return;await change('disable',{});await loadProject();}));}const f=formBox(overview,'Project status',async()=>change('status',{status:status.value}));const status=field(f,'Status','status','text',['Planning','In progress','Review','Delivered','On hold']);status.value=p.status;}
 const proposals=el('section');proposals.append(el('h2','Proposals & agreed scope'));root.append(proposals);
 if(staff){const f=formBox(proposals,'Create an immutable proposal revision',async()=>{if(!expiry.value)throw Error('Choose an expiry date.');await change('proposal',{title:title.value,scope:scope.value,terms:terms.value,value:amount.value,currency:currency.value,expires:Math.floor(Date.parse(expiry.value+'T23:59:59+05:30')/1000)});});const title=field(f,'Title','title'),scope=field(f,'Scope and deliverables','scope','textarea'),terms=field(f,'Commercial terms, responsibilities and payment milestones','terms','textarea'),amount=field(f,'Proposal value','value','number'),currency=field(f,'Currency','currency','text',['INR','USD','GBP','EUR','AED']),expiry=field(f,'Valid until (India date)','expires','date');title.maxLength=160;scope.maxLength=terms.maxLength=2500;amount.min='0';amount.step='0.01';for(const v of [title,scope,terms,amount,expiry])v.required=true;}
 if(!p.proposals.length)proposals.append(el('p','No proposals yet.'));
 for(const proposal of p.proposals){const a=el('article');a.append(el('h3',proposal.title+' · revision '+proposal.revision),el('p',proposal.status+' · '+money(proposal)+' · Valid until '+stamp(proposal.expires)),el('h4','Scope'),el('p',proposal.scope,'copy'),el('h4','Commercial terms'),el('p',proposal.terms,'copy'));if(proposal.accepted)a.append(el('p','Accepted '+stamp(proposal.accepted)+' by '+proposal.accepted_by));
  if(staff&&proposal.status==='draft')a.append(button('Publish this revision',async()=>{if(!confirm('Publish this exact scope and amount, and notify the client?'))return;await change('publish',{id:proposal.id});await loadProject();}));
  if(staff&&['draft','published'].includes(proposal.status))a.append(button('Withdraw',async()=>{if(!confirm('Withdraw this proposal?'))return;await change('withdraw',{id:proposal.id});await loadProject();}));
  if(!staff&&proposal.status==='published'&&proposal.expires>Date.now()/1000){const f=formBox(a,'Accept this proposal',async()=>{await change('accept',{id:proposal.id,name:name.value,agree:agree.checked});});const name=field(f,'Your full name','name');name.required=true;name.maxLength=120;const agree=field(f,'I accept the scope, value and commercial terms of revision '+proposal.revision,'agree','checkbox');agree.required=true;}
  proposals.append(a);}
 const milestones=el('section');milestones.append(el('h2','Project milestones'));root.append(milestones);
 if(staff){const f=formBox(milestones,'Add or update a milestone',async()=>change('milestone',{id:id.value||undefined,title:title.value,due:due.value,status:status.value,notes:notes.value}));const id=field(f,'Milestone ID (leave blank to add)','id'),title=field(f,'Title','title'),due=field(f,'Target date','due','date'),status=field(f,'Status','status','text',['Planned','In progress','Ready for review','Approved','Complete']),notes=field(f,'Client-visible update','notes','textarea');title.required=true;title.maxLength=160;notes.maxLength=1500;}
 for(const m of p.milestones){const a=el('article');a.append(el('h3',m.title),el('p',m.status+' · Target '+(m.due||'Not set')),el('p',m.notes,'copy'));if(staff)a.append(el('small','ID: '+m.id));if(!staff&&m.status==='Ready for review')a.append(button('Approve milestone',async()=>{if(!confirm('Approve '+m.title+'?'))return;await change('approve-milestone',{id:m.id});await loadProject();}));milestones.append(a);}if(!p.milestones.length)milestones.append(el('p','No milestones recorded.'));
 const documents=el('section');documents.append(el('h2','Private documents'));root.append(documents);
 if(staff){const f=formBox(documents,'Upload a project document',async()=>{const file=input.files[0];if(!file||file.size>512*1024)throw Error('Choose a file up to 512 KB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await change('document',{name:file.name,content:btoa(binary)});});const input=field(f,'PDF, UTF-8 text, PNG or JPG; up to 512 KB','file','file');input.accept='.pdf,.txt,.png,.jpg,.jpeg';input.required=true;}
 for(const d of p.documents){const a=el('p'),link=el('a',d.name+' · '+Math.ceil(d.size/1024)+' KB');link.href=prefix+'document?id='+encodeURIComponent(d.id);a.append(link);if(staff)a.append(' ',button('Remove access',async()=>{if(!confirm('Remove client access to this document?'))return;await change('remove-document',{id:d.id});await loadProject();}));documents.append(a);}if(!p.documents.length)documents.append(el('p','No documents shared.'));
 const tickets=el('section');tickets.append(el('h2','Support requests'));root.append(tickets);
 if(!staff){const f=formBox(tickets,'New support request',async()=>change('ticket',{subject:subject.value,priority:priority.value,body:body.value}));const subject=field(f,'Subject','subject'),priority=field(f,'Priority','priority','text',['Normal','Urgent']),body=field(f,'Describe the request','body','textarea');subject.required=body.required=true;subject.maxLength=160;body.maxLength=2500;f.append(el('p','Priority sets an internal follow-up target; your agreed support contract governs response commitments.','muted'));}
 for(const t of p.tickets){const a=el('article');a.append(el('h3',t.subject),el('p',t.status+' · '+t.priority+(staff?' · Owner '+t.owner+' · Internal target '+stamp(t.due):'')));for(const m of t.messages){const n=el('div',undefined,m.internal?'internal':'');n.append(el('small',m.actor+' · '+stamp(m.created)+(m.internal?' · Staff only':'')),el('p',m.body,'copy'));a.append(n);}const f=formBox(a,staff?'Reply or add an internal note':'Reply to this request',async()=>change('ticket',{id:t.id,ticketVersion:t.version,body:body.value,...(staff?{status:status.value,owner:owner.value,internal:internal.checked}:{})}));const body=field(f,'Message','body','textarea');body.required=true;body.maxLength=2500;let status,owner,internal;if(staff){status=field(f,'Status','status','text',['Open','In progress','Waiting for client','Closed']);status.value=t.status;owner=field(f,'Assigned staff email','owner','email');owner.value=t.owner;owner.required=true;internal=field(f,'Staff-only note (not visible to client)','internal','checkbox');}tickets.append(a);}if(!p.tickets.length)tickets.append(el('p','No support requests.'));
}
async function enter(identity){csrf=identity.csrf;role=identity.role||'';$('login').hidden=true;if($('activate'))$('activate').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;await load();}
if(!staff){$('login-form').addEventListener('submit',e=>{e.preventDefault();const b=e.submitter;b.disabled=true;act(async()=>{await enter(await api(prefix+'login',{email:$('email').value,password:$('password').value}));$('password').value='';},'Signed in.').finally(()=>{b.disabled=false;$('password').value='';});});$('activate-form').addEventListener('submit',e=>{e.preventDefault();const b=e.submitter;b.disabled=true;act(async()=>{if($('new-password').value!==$('repeat-password').value)throw Error('Passwords do not match.');await enter(await api(prefix+'activate',{token:invite,password:$('new-password').value}));invite=null;},'Workspace access activated.').finally(()=>{b.disabled=false;$('new-password').value=$('repeat-password').value='';});});}
if(staff){const ref=new URLSearchParams(location.search).get('reference')||'';$('reference').value=$('meeting-reference').value=$('loss-reference').value=ref;$('create-form').addEventListener('submit',e=>{e.preventDefault();const b=e.submitter;b.disabled=true;act(async()=>{await api(prefix+'create',{reference:$('reference').value,title:$('project-title').value});await load();$('project-list').value=$('reference').value;await loadProject();},'Project created.').finally(()=>b.disabled=false);});$('meeting-form').addEventListener('submit',e=>{e.preventDefault();const b=e.submitter;b.disabled=true;act(async()=>{const reference=$('meeting-reference').value,a=await api(prefix+'appointment?reference='+encodeURIComponent(reference));await api(prefix+'meeting',{reference,version:a.version,url:$('meeting-url').value});},'Meeting link saved. The customer update is queued.').finally(()=>b.disabled=false);});$('loss-form').addEventListener('submit',e=>{e.preventDefault();act(async()=>{await api(prefix+'loss',{reference:$('loss-reference').value,reason:$('loss-reason').value});await report();});});$('report-days').addEventListener('change',()=>act(report,''));}
$('refresh').addEventListener('click',()=>act(load,''));$('project-list').addEventListener('change',()=>act(loadProject,''));$('logout').addEventListener('click',()=>act(async()=>{await api(staff?'/api/admin/logout':prefix+'logout',{});clear();},'Signed out.'));
if(!invite)act(async()=>{const state=await api(staff?'/api/admin/session':prefix+'session');if(state.authenticated)await enter(state);},'');
