'use strict';
const $=id=>document.getElementById(id), stages=['New','Contacted','Proposal','Won','Lost'];
let csrf='',offset=0,total=0,current=null,loading=false;
function text(tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;return el;}
function loggedOut(message=''){csrf='';current=null;$('editor').close();$('entries').replaceChildren();$('details').replaceChildren();$('counts').replaceChildren();$('editor-heading').textContent='';$('editor-reference').textContent='';$('customer-message').textContent='';$('owner').value='';$('notes').value='';$('workspace').hidden=true;$('logout').hidden=true;$('login').hidden=false;$('login-message').textContent=message;}
async function api(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{credentials:'same-origin',cache:'no-store',signal:controller.signal,...options});const result=await response.json();if(!response.ok){if(response.status===401&&url!=='/api/admin/login')loggedOut(result.error);throw Error(result.error||'Unable to complete this action.');}return result;}finally{clearTimeout(timer);}}
function post(url,body){return api(url,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)});}
function date(timestamp){return new Date(timestamp*1000).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});}
async function load(){if(loading)return;loading=true;$('refresh').disabled=true;$('inbox-message').textContent='Loading enquiries…';try{const query=new URLSearchParams({q:$('search').value.trim(),stage:$('stage-filter').value,offset:String(offset)});const result=await api('/api/admin/enquiries?'+query);total=result.total;$('entries').replaceChildren();$('counts').replaceChildren(...stages.map(stage=>{const node=text('div','', 'count');node.append(text('span',stage),text('strong',String(result.counts[stage])));return node;}));$('mail-status').textContent=result.emailConfigured?'Email sender configured. Check each request’s notification status; delivery may still be pending.':'Email notifications are pending setup. Requests are saved here; review this inbox regularly until the email sender is connected.';$('mail-status').classList.toggle('connected',result.emailConfigured);$('total').textContent=total+' matching '+(total===1?'request':'requests');for(const entry of result.items){const card=document.createElement('button');card.type='button';card.className='entry';const summary=document.createElement('div');summary.append(text('h3',entry.details.name),text('p',entry.details.interest),text('p',entry.reference+' · '+entry.details.email),text('p',entry.owner?'Owner: '+entry.owner:'No owner assigned'));const aside=document.createElement('aside');aside.append(text('span',entry.stage,'stage'),text('time',date(entry.created)));card.append(summary,aside);card.addEventListener('click',()=>edit(entry));$('entries').append(card);}if(!result.items.length)$('entries').append(text('p',total?'No requests on this page. Go back to the previous page.':'No enquiries match these filters.','empty'));$('previous').disabled=offset===0;$('next').disabled=offset+50>=total;$('page-label').textContent=total?Math.min(offset+1,total)+'–'+Math.min(offset+50,total)+' of '+total:'0 requests';$('inbox-message').textContent='';}catch(error){$('inbox-message').textContent=error.name==='AbortError'?'Loading timed out. Try refreshing.':error.message;}finally{loading=false;$('refresh').disabled=false;}}
function edit(entry){current=entry;$('editor-heading').textContent=entry.details.name;$('editor-reference').textContent=entry.reference+' · '+date(entry.created);$('details').replaceChildren();for(const [label,value]of [['Email',entry.details.email],['Phone',entry.details.phone],['Service',entry.details.interest],['Request type',entry.details.type],['Source',entry.details.source],['Campaign',entry.details.campaign],['Notification',entry.emailStatus],['Last follow-up',entry.updated?date(entry.updated):'Not yet updated']]){if(value)$('details').append(text('dt',label),text('dd',value));}$('customer-message').textContent=entry.details.message;$('edit-stage').value=entry.stage;$('owner').value=entry.owner;$('notes').value=entry.notes;$('save-message').textContent='';$('editor').showModal();}
async function showInbox(){ $('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('password').value='';offset=0;await load(); }
$('login-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$('login-message').textContent='Signing in…';try{const result=await post('/api/admin/login',{email:$('email').value,password:$('password').value});csrf=result.csrf;await showInbox();}catch(error){$('login-message').textContent=error.name==='AbortError'?'Sign-in timed out. Please try again.':error.message;}finally{button.disabled=false;$('password').value='';}});
$('workflow').addEventListener('submit',async event=>{event.preventDefault();if(!current)return;const button=event.submitter;button.disabled=true;$('save-message').textContent='Saving…';try{const result=await post('/api/admin/update',{reference:current.reference,stage:$('edit-stage').value,owner:$('owner').value,notes:$('notes').value,version:current.version});current.version=result.version;$('save-message').textContent='Follow-up saved.';await load();}catch(error){$('save-message').textContent=error.name==='AbortError'?'Unable to confirm the save. Refresh before retrying; your notes are retained here.':error.message;}finally{button.disabled=false;}});
$('filters').addEventListener('submit',event=>{event.preventDefault();offset=0;load();});$('refresh').addEventListener('click',()=>load());$('previous').addEventListener('click',()=>{offset=Math.max(0,offset-50);load();});$('next').addEventListener('click',()=>{offset+=50;load();});$('close-editor').addEventListener('click',()=>$('editor').close());$('logout').addEventListener('click',async()=>{try{await post('/api/admin/logout',{});loggedOut('You are signed out.');}catch(error){$('inbox-message').textContent=error.message;}});
(async()=>{try{const state=await api('/api/admin/session');if(state.authenticated){csrf=state.csrf;await showInbox();}else if(!state.configured){$('login-message').textContent='Dashboard access needs to be set up by the site owner.';$('login-form').hidden=true;}}catch(error){$('login-message').textContent='The inbox is temporarily unavailable. Please try again.';}})();
