const {chromium}=require('playwright'),{spawn}=require('node:child_process'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=process.env.INBOX_QA_OUTPUT||path.join(root,'qa-results');fs.mkdirSync(output,{recursive:true});
const service=spawn(process.env.QA_PYTHON||'python3',['-B',path.join(root,'server','test_inbox_preview.py')],{cwd:root,stdio:['ignore','pipe','pipe']});
const ready=new Promise((resolve,reject)=>{let text='';service.stdout.on('data',b=>{text+=b.toString();if(/^\d+\s/.test(text))resolve('http://127.0.0.1:'+text.trim());});service.once('error',reject);service.once('exit',c=>reject(Error('Fixture stopped: '+c)));setTimeout(()=>reject(Error('Fixture startup timed out')),15000).unref();});
(async()=>{let browser;const checks=[],errors=[];try{
const base=await ready;browser=await chromium.launch(process.env.QA_CHROME?{executablePath:process.env.QA_CHROME}:{});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function login(email){await page.goto(base+'/team-inbox/');await page.locator('#email').fill(email);await page.locator('#password').fill('Synthetic-dashboard-only-20261010');await page.locator('#login-form button').click();await page.locator('#entries .entry').first().waitFor();}
await login('sales@bandeviglobalgroup.com');assert(await page.locator('#workspace-nav').isVisible());assert.equal(await page.locator('#entries .entry').count(),3);assert((await page.locator('#entries .entry').first().boundingBox()).y<800);checks.push('Persistent signed-in navigation and enquiries above the desktop fold');
await page.getByRole('button',{name:'Reports',exact:true}).click();assert(await page.locator('#panel-reports').isVisible());assert(await page.locator('#panel-inbox').isHidden());await page.getByRole('button',{name:'Demos',exact:true}).click();assert(await page.locator('#slot-form').isVisible());await page.getByRole('button',{name:'Settings',exact:true}).click();assert(await page.locator('#staff-form').isVisible());await page.getByRole('button',{name:'Inbox',exact:true}).click();checks.push('Report, demo and settings views');
await page.getByRole('button',{name:'New: 1 enquiries',exact:true}).click();await page.locator('#total').filter({hasText:'1 matching request'}).waitFor();assert.equal(await page.locator('#entries .entry').count(),1);assert.equal(await page.locator('#stage-filter').inputValue(),'New');assert.equal(await page.getByRole('button',{name:'New: 1 enquiries',exact:true}).getAttribute('aria-pressed'),'true');checks.push('Stage counter filters enquiries');
await page.locator('#clear-filters').click();await page.locator('#total').filter({hasText:'3 matching requests'}).waitFor();await page.getByRole('button',{name:'Due today: 1 active follow-ups',exact:true}).focus();await page.keyboard.press('Enter');await page.locator('#total').filter({hasText:'1 matching request'}).waitFor();assert.equal(await page.locator('#entries .entry').first().getAttribute('data-reference'),'BG-QA-TODAY');assert.equal(await page.locator('#stage-filter').inputValue(),'');checks.push('Keyboard follow-up filter clears conflicting stage');
await page.locator('#clear-filters').click();await page.locator('#total').filter({hasText:'3 matching requests'}).waitFor();const lead=page.locator('[data-reference="BG-QA-NEW"]');await lead.getByRole('button',{name:'Assign owner',exact:true}).click();await page.locator('#editor[open]').waitFor();assert(await page.locator('#owner').evaluate(e=>e===document.activeElement));await page.locator('#owner').fill('sales@bandeviglobalgroup.com');await page.locator('#workflow button[type=submit]').click();await page.getByText('Follow-up saved.',{exact:true}).waitFor();await page.locator('#close-editor').click();await lead.getByText('Owner: sales@bandeviglobalgroup.com',{exact:true}).waitFor();checks.push('Assignment quick action focuses and saves through existing workflow');
await lead.getByRole('button',{name:'Follow-up',exact:true}).click();assert(await page.locator('#follow-up-date').evaluate(e=>e===document.activeElement));await page.locator('#close-editor').click();checks.push('Follow-up quick action focuses the date');
await page.locator('#attention-action').click();await page.locator('#total').filter({hasText:'2 matching requests'}).waitFor();assert.equal(await page.locator('#followup-filter').inputValue(),'attention');assert.equal(await page.locator('#attention-action').getAttribute('aria-pressed'),'true');checks.push('Attention queue excludes closed leads and explains missing actions');
await lead.getByRole('button',{name:'Open',exact:true}).click();await page.locator('#activity-list').getByText('Enquiry received.',{exact:true}).waitFor();await page.locator('#next-action').fill('Call to confirm scope');await page.locator('#follow-up-date').fill('2030-01-12');await page.locator('#edit-stage').selectOption('Contacted');await page.locator('#workflow button[type=submit]').click();await page.getByText('Follow-up saved.',{exact:true}).waitFor();await page.locator('#activity-list').getByText(/Next action: Not set → Call to confirm scope/).waitFor();
await page.locator('#activity-kind').selectOption('call-no-answer');await page.locator('#activity-body').fill('<script>window.unexpectedActivity=true</script> No answer; retry tomorrow.');await page.locator('#activity-form button').click();await page.getByText('Activity recorded.',{exact:true}).waitFor();await page.locator('#activity-list').getByText('<script>window.unexpectedActivity=true</script> No answer; retry tomorrow.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.unexpectedActivity),undefined);checks.push('Next-action save and append-only call timeline render unsafe text safely');
await page.locator('#close-editor').click();await page.locator('#total').filter({hasText:'1 matching request'}).waitFor();assert.equal(await page.locator('#entries .entry').first().getAttribute('data-reference'),'BG-QA-TODAY');await page.locator('#clear-filters').click();await page.locator('#total').filter({hasText:'3 matching requests'}).waitFor();await lead.getByText('Next action: Call to confirm scope',{exact:true}).waitFor();await lead.getByRole('button',{name:'Open',exact:true}).click();assert.equal(await page.locator('#edit-stage').inputValue(),'Contacted');await page.locator('#activity-list').getByText('Call — no answer',{exact:true}).waitFor();await page.locator('#close-editor').click();checks.push('Completed ownership and next step remove an active lead from attention without auto-changing call outcomes');
await page.locator('[data-reference="BG-QA-TODAY"]').getByRole('link',{name:'Project / proposal',exact:true}).click();await page.getByRole('heading',{name:'Correct enquiry project',exact:true}).waitFor();assert.equal(await page.locator('#project-list').inputValue(),'BG-QA-TODAY');assert(await page.locator('#proposals').isVisible());checks.push('Proposal handoff selects the correct existing enquiry project');
await page.goto(base+'/team-inbox/workspace/?reference=BG-QA-NEW&title=CRM%20project#proposals');await page.locator('#workspace').waitFor();await page.getByText('No projects are available.',{exact:true}).waitFor();assert.equal(await page.locator('#project-list').inputValue(),'');assert.equal(await page.locator('#reference').inputValue(),'BG-QA-NEW');assert.equal(await page.locator('#project-title').inputValue(),'CRM project');assert(await page.locator('#create-form').isVisible());assert.equal(await page.getByRole('heading',{name:'Different enquiry project',exact:true}).count(),0);checks.push('Missing project opens creation without selecting another client');
await page.goto(base+'/team-inbox/');await page.locator('#entries .entry').first().waitFor();for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await page.getByRole('link',{name:'Projects',exact:true}).isVisible());await page.screenshot({path:path.join(output,'inbox-'+width+'.png'),fullPage:false});}checks.push('Compact navigation and layout at four screen widths');
await page.locator('#logout').click();await page.locator('#login').waitFor();assert(await page.locator('#workspace-nav').isHidden());assert.equal(await page.locator('#entries').textContent(),'');checks.push('Sign-out hides navigation and clears private enquiry content');
await login('agent@qa.example');assert(await page.locator('#nav-settings').isHidden());assert(await page.locator('#nav-demos').isHidden());assert.equal(await page.getByRole('button',{name:'Assign owner',exact:true}).count(),0);assert.equal(await page.locator('#entries .entry').count(),1);await page.getByRole('button',{name:'Follow-up',exact:true}).click();assert(await page.locator('#owner').evaluate(e=>e.readOnly));await page.locator('#close-editor').click();checks.push('Agent navigation and quick actions preserve role restrictions');
await page.locator('#logout').click();await page.locator('#login').waitFor();await login('sales@bandeviglobalgroup.com');let release;
const gate=new Promise(resolve=>release=resolve);let held=false;await page.route('**/api/admin/enquiries?*',async route=>{if(held)return route.continue();held=true;const response=await route.fetch();await gate;await route.fulfill({response});});
await page.locator('#refresh').click();await page.waitForFunction(()=>document.getElementById('refresh').disabled);await page.locator('#logout').click();await page.locator('#login').waitFor();await page.locator('#email').fill('agent@qa.example');await page.locator('#password').fill('Synthetic-dashboard-only-20261010');await page.locator('#login-form button').click();await page.locator('#workspace-nav').waitFor();release();await page.locator('#entries .entry').first().waitFor();assert.equal(await page.locator('#entries .entry').count(),1);assert.equal(await page.locator('#entries .entry').first().getAttribute('data-reference'),'BG-QA-TODAY');await page.unroute('**/api/admin/enquiries?*');checks.push('Delayed administrator responses cannot populate a later agent session');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'inbox-results.json'),JSON.stringify({checks,errors},null,2));console.log('PASS: '+checks.length+' inbox browser scenarios');
}finally{if(browser)await browser.close();service.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
